import json
from dataclasses import dataclass, asdict
from typing import List, Dict, Optional, Any

@dataclass
class Action:
    """
    Represents a single executable action in the Action Planner DAG.
    """
    id: str
    title: str
    cost: float # e.g., computational cost or business cost (dollars)
    latency: float # expected execution time (e.g., seconds)
    dependencies: List[str] # List of Action IDs that must complete before this one starts
    rollback_action: Optional[str] # Description or ID of the action to revert these changes

@dataclass
class ActionPlan:
    """
    Represents a complete action plan (Directed Acyclic Graph) generated by the Planner.
    """
    plan_id: str
    insight_id: str
    actions: List[Action]

    def to_dict(self) -> Dict[str, Any]:
        """Converts the ActionPlan to a JSON-compatible Python dictionary."""
        return asdict(self)
        
    def to_json(self) -> str:
        """Converts the ActionPlan to a formatted JSON string."""
        return json.dumps(self.to_dict(), indent=2)

class ActionPlanner:
    """
    Module responsible for taking resolved business insights and generating 
    a connected execution DAG of actions to address the insight.
    """
    
    def __init__(self):
        # Initialization could include loading action templates, policies, or cost models.
        pass

    def generate_plan_for_anomaly(self, insight_id: str, anomaly_details: Dict[str, Any]) -> ActionPlan:
        """
        Generates a predefined DAG of actions to handle a regional sales anomaly.
        
        Args:
            insight_id: The unique identifier of the resolved business insight.
            anomaly_details: Contextual details about the anomaly (e.g., region, drop %).
            
        Returns:
            An ActionPlan object containing the execution DAG.
        """
        
        # 1. Diagnose
        # Root node: Needs to happen first to deeply understand the anomaly's root cause.
        diagnose_action = Action(
            id="act_001",
            title="Diagnose Sales Anomaly",
            cost=50.0,
            latency=300.0,
            dependencies=[], # No dependencies, starts immediately
            rollback_action=None # Diagnostics usually don't need rollbacks
        )

        # 2. Notify Managers
        # Depends on diagnosis so we can include the root cause in the notification.
        notify_action = Action(
            id="act_002",
            title="Notify Regional Managers",
            cost=5.0,
            latency=10.0,
            dependencies=["act_001"],
            rollback_action="Send cancellation/correction follow-up email"
        )

        # 3. Update Pricing
        # If the anomaly is competitive, we may need to adjust regional pricing.
        # Depends on Diagnosis completing first.
        update_pricing_action = Action(
            id="act_003",
            title="Update Regional Pricing",
            cost=100.0, # Higher cost due to direct business impact
            latency=60.0,
            dependencies=["act_001"],
            rollback_action="Revert pricing to previous baseline state"
        )

        # 4. Launch Campaign
        # To win back lost sales velocity, launch a targeted regional campaign.
        # Depends on Update Pricing (we want the new prices reflected in the campaign).
        launch_campaign_action = Action(
            id="act_004",
            title="Launch Targeted Win-back Campaign",
            cost=500.0, # Significant marketing spend
            latency=3600.0, # Takes time to deploy
            dependencies=["act_003"],
            rollback_action="Pause or cancel active campaign"
        )

        # 5. Schedule Monitor
        # Monitor the effects of our mitigation actions over time.
        # Depends on the notification and campaign launch being initiated.
        schedule_monitor_action = Action(
            id="act_005",
            title="Schedule Anomaly Resolution Monitor",
            cost=20.0,
            latency=5.0,
            dependencies=["act_002", "act_004"],
            rollback_action="Cancel scheduled monitoring task"
        )

        # Assemble the DAG
        actions = [
            diagnose_action,
            notify_action,
            update_pricing_action,
            launch_campaign_action,
            schedule_monitor_action
        ]

        # Create and return the action plan
        plan = ActionPlan(
            plan_id=f"plan_for_{insight_id}",
            insight_id=insight_id,
            actions=actions
        )

        return plan

if __name__ == "__main__":
    # Example usage / testing
    planner = ActionPlanner()
    mock_anomaly_data = {"region": "US-West", "sales_drop_percentage": 15}
    
    # Generate the plan based on a mock insight
    plan = planner.generate_plan_for_anomaly("insight_8492A", mock_anomaly_data)
    
    # Output the JSON-compatible result
    print("Generated Action Plan DAG (JSON):")
    print(plan.to_json())
